/*
output "waf_domain_id" {
  description = "ID of the WAF domain."
  value       = huaweicloud_waf_domain.this.id
}

output "waf_domain_name" {
  description = "The protected domain name."
  value       = huaweicloud_waf_domain.this.domain
}

output "waf_cname" {
  description = "CNAME value generated by WAF. Point your DNS CNAME record here so traffic flows through WAF → ELB."
  value       = huaweicloud_waf_domain.this.access_code
}

output "waf_policy_id" {
  description = "ID of the WAF protection policy."
  value       = huaweicloud_waf_policy.this.id
}
*/